package com.googlecode.blacken.terminal;

public enum BlackenEventType {
    MOUSE_CLICKED, 
    MOUSE_ENTERED, 
    MOUSE_EXITED, 
    MOUSE_PRESSED, 
    MOUSE_DRAGGED, 
    MOUSE_MOVED, 
    WINDOW_ACTIVATED, 
    WINDOW_CLOSED, 
    WINDOW_CLOSING, 
    WINDOW_DEACTIVATED, 
    WINDOW_DEICONIFIED, 
    WINDOW_ICONIFIED, 
    WINDOW_OPENED, 
    WINDOW_GAINED_FOCUS, 
    WINDOW_LOST_FOCUS, MOUSE_WHEEL, MOUSE_RELEASED,
}
